// Generated by: rad bicep generate --from-aspire
// Source: ../example-aspire-app/
// Date: 2026-02-26T22:10:30Z

extension radius

@description('The ID of your Radius Environment. Set automatically by the rad CLI.')
param environment string

@description('The name of the Radius Application.')
param applicationName string = 'example-aspire-app'

@description('Container image for apiservice.')
param apiserviceImage string = 'my-namespace/aspireapp-apiservice:latest'

@description('Container image for webfrontend.')
param webfrontendImage string = 'my-namespace/aspireapp-web:latest'

resource app 'Applications.Core/applications@2023-10-01-preview' = {
  name: applicationName
  properties: {
    environment: environment
  }
}

resource apiservice 'Applications.Core/containers@2023-10-01-preview' = {
  name: 'apiservice'
  properties: {
    application: app.id
    environment: environment
    container: {
      image: apiserviceImage
      ports: {
        http: {
          containerPort: 8080
          protocol: 'TCP'
        }
      }
      env: {
        ASPNETCORE_FORWARDEDHEADERS_ENABLED: { value: 'true' }
        ConnectionStrings__weatherdb: { value: sqlserver.listSecrets().connectionString }
        HTTP_PORTS: { value: '8080' }
        OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: { value: 'true' }
        OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: { value: 'true' }
        OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: { value: 'in_memory' }
        WEATHERDB_DATABASENAME: { value: sqlserver.properties.database }
        WEATHERDB_HOST: { value: sqlserver.properties.server }
        WEATHERDB_PASSWORD: { value: sqlserver.listSecrets().password }
        WEATHERDB_PORT: { value: string(sqlserver.properties.port) }
        WEATHERDB_USERNAME: { value: sqlserver.properties.username }
      }
    }
    connections: {
      sqlserver: {
        source: sqlserver.id
      }
    }
  }
}

resource webfrontend 'Applications.Core/containers@2023-10-01-preview' = {
  name: 'webfrontend'
  properties: {
    application: app.id
    environment: environment
    container: {
      image: webfrontendImage
      ports: {
        http: {
          containerPort: 8080
          protocol: 'TCP'
        }
      }
      env: {
        ASPNETCORE_FORWARDEDHEADERS_ENABLED: { value: 'true' }
        CACHE_HOST: { value: cache.properties.host }
        CACHE_PORT: { value: string(cache.properties.port) }
        ConnectionStrings__cache: { value: cache.listSecrets().connectionString }
        HTTP_PORTS: { value: '8080' }
        OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: { value: 'true' }
        OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: { value: 'true' }
        OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: { value: 'in_memory' }
        services__apiservice__http__0: { value: 'http://apiservice:8080' }
        services__apiservice__https__0: { value: 'https://apiservice:8080' }
      }
    }
    connections: {
      apiservice: {
        source: apiservice.id
      }
      cache: {
        source: cache.id
      }
    }
  }
}

resource cache 'Applications.Datastores/redisCaches@2023-10-01-preview' = {
  name: 'cache'
  properties: {
    application: app.id
    environment: environment
  }
}

resource sqlserver 'Applications.Datastores/sqlDatabases@2023-10-01-preview' = {
  name: 'sqlserver'
  properties: {
    application: app.id
    environment: environment
  }
}

